# Generated by Django 2.1.7 on 2019-03-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('IN', 'Insects'), ('FR', 'Frogs'), ('FI', 'Fish')], default='IN', max_length=2)),
                ('kingfisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Kingfisher')),
            ],
        ),
    ]
